# Setup
title:               Nicholas Vadivelu
# tagline:             'test'
# description:         'test'
url:                 'https://nicholasvadivelu.com'
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Nicholas Vadivelu
  url:               https://twitter.com/nicvadivelu
  email:             nicholas.vadivelu@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: UA-176806209-1
