# Setup
title:               Nicholas Vadivelu
tagline:             ''
description:         ''
url:                 https://n2cholas.github.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nicholas Vadivelu
  url:               https://twitter.com/nicvadivelu
  email:             nicholas.vadivelu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
